Repository MicroShed/microshed-testing, pull requests merged in 2020-01, with the labels that each got.

#128 Introduce WildFly module
  modules/wildfly/build.gradle
  modules/wildfly/src/main/java/org/testcontainers/containers/wildfly/WildFlyAdapter.java
  modules/wildfly/src/main/resources/META-INF/services/org.microshed.testing.testcontainers.spi.ServerAdapter
  modules/wildfly/src/main/resources/log4j.properties
  sample-apps/wildfly-app/Dockerfile
  sample-apps/wildfly-app/build.gradle
Labels: is:enhancement

#129 Update to version 0.6.3-SNAPSHOT
  README.md
  build.gradle
  docs/features/00_Walkthrough.md
  docs/features/01_SupportedRuntimes.md
  docs/index.md
  modules/wildfly/src/main/java/org/testcontainers/containers/wildfly/WildFlyAdapter.java
  sample-apps/maven-app/pom.xml
Labels: is:housekeeping

#134 Integration with REST-assured
  core/src/main/java/org/microshed/testing/jupiter/MicroShedTestExtension.java
  docs/features/14_RestAssured.md
  docs/features/98_Examples.md
  sample-apps/everything-app/build.gradle
  sample-apps/everything-app/src/test/java/org/example/app/RestAssuredTest.java
Labels: is:enhancement

#138 Upgrade to JUnit Jupiter 5.6.0
  core/build.gradle
  docs/features/00_Walkthrough.md
  docs/index.md
  modules/testcontainers/build.gradle
  sample-apps/everything-app/build.gradle
  sample-apps/jaxrs-json/build.gradle
  sample-apps/jaxrs-mpjwt/build.gradle
  sample-apps/jdbc-app/build.gradle
  sample-apps/liberty-app/build.gradle
  sample-apps/maven-app/pom.xml
  sample-apps/payara-app/build.gradle
  sample-apps/wildfly-app/build.gradle
Labels: dependencies
